# -*- coding: utf-8 -*-
"""Entrenamiento_AGV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFFMAJ21dECwyzDb1__H4At_MaghZi24
"""

import ultralytics
ultralytics.checks()

from roboflow import Roboflow
rf = Roboflow(api_key="v2IQq1oAlcKaEwuoR0RK")
project = rf.workspace("dilans-workspace-zoskt").project("agv_detection")
version = project.version(2)
dataset = version.download("yolov8")

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.train(data=f'{dataset.location}/data.yaml', epochs=30, imgsz=640)

import glob
from IPython.display import Image, display

test_images = glob.glob(f'{dataset.location}/test/images/*.jpg')

if len(test_images) > 0:
    res = model.predict(source=test_images[0], save=True)

    display(Image(filename=res[0].save_dir + '/' + test_images[0].split('/')[-1]))
else:
    print("No se encontraron imágenes de prueba.")

import glob
import random
from IPython.display import Image, display

test_images = glob.glob(f'{dataset.location}/test/images/*.jpg')

cantidad_a_mostrar = min(10, len(test_images))

if cantidad_a_mostrar > 0:
    imagenes_al_azar = random.sample(test_images, cantidad_a_mostrar)

    print(f"Evaluando {cantidad_a_mostrar} imágenes al azar de tu pista...\n")

    for ruta_img in imagenes_al_azar:
        res = model.predict(source=ruta_img, save=True)

        ruta_guardada = res[0].save_dir + '/' + ruta_img.split('/')[-1]

        display(Image(filename=ruta_guardada))
        print("-" * 50)
else:
    print("No se encontraron imágenes de prueba en la carpeta.")